= Test 2 - Web Access Log Parsing

== Requirements

Consume web access log files and emit the following metrics:

* No. of successful requests per minute
* No. of error requests per minute
* Mean response time per minute
* MBs sent per minute


== Data

Solution developed with this data : https://s3-eu-west-1.amazonaws.com/skyscanner-recruitement-resources/devops/access-log-example/c930ecf4b0a4426e619bddd8752c475ea772427db13eb92ee6a1a79b248ec0dc/access.log[access.log]

=== Log format

As http://httpd.apache.org/docs/2.2/mod/mod_log_config.html[Defined here] : "%a %l %u %t \"%r\" %>s %b %D"

Parse with https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/grok-patterns[Logstash] using `%{COMMONAPACHELOG} %{BASE10NUM:time_to_serve}`.

== Decisions

=== Technology

Going with Logstash for the parsing as parsing Apache logs is a standard task
for Logstash and is tried and tested.

== Testing

Take a small part of the log and manually count the up the values and use that
for testing.

== Running

=== Parse the data

    ./scripts/run_logstash.sh
    ./scripts/write_to_log.sh

== Plan

* Get the sample logs
* Write the requirements
* Decide technology for solution
* Create logstash conf to parse the logs
* Done =========================================
* Set up testing
* Get the numbers
* Add any missing documentation

=== Getting the numbers

To get the information from the data try these solutions in order:

* Logstash metrics plugin
** The default seems to be that this will give you rates based on when entries are added to the logs. I cannot find a way to use the timestamp in the log.
** I have found a way to set the Logstash timestamp to the timestamp value from the original log but the rates are per second.
** I looked through all the other filter plugins and could not find anything suitable.
* Elastic Search
** I tried this using aggregation but I could not work out how to get the values a per minute.
** I am going to give up and go with the scripting option.
* take the json output from logstash and do write a script
